on: [push]

jobs:
  build-secure-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      
    - uses: Azure/container-scan@v0
      continue-on-error: true
      with:
        image-name: mcr.microsoft.com/dotnet/runtime-deps:3.1

    - uses: Azure/container-scan@v0
      continue-on-error: true
      with:
        image-name: mcr.microsoft.com/dotnet/runtime-deps:3.1-bionic

    - uses: Azure/container-scan@v0
      continue-on-error: true
      with:
        image-name: mcr.microsoft.com/azure-functions/dotnet:3.0
        
    - uses: Azure/container-scan@v0
      continue-on-error: true
      with:
        image-name: mcr.microsoft.com/dotnet/aspnet:3.1-alpine
        
    - uses: Azure/container-scan@v0
      continue-on-error: true
      with:
        image-name: mcr.microsoft.com/dotnet/aspnet:3.1-bionic
